# Generated by Django 3.2.16 on 2023-01-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(default='steve', max_length=100),
            preserve_default=False,
        ),
    ]
