# Generated by Django 3.2.16 on 2023-01-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('companies', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(related_name='following_companies', through='companies.Test', to='students.Student'),
        ),
        migrations.AddField(
            model_name='test',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
