# Generated by Django 3.2.16 on 2023-01-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
