# Generated by Django 3.2.16 on 2023-01-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20230111_1603'),
        ('students', '0001_initial'),
        ('observers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
